name: Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_12.app
      - name: test
        run: | 
          echo ${{ github.base_ref }} # GITHUB_BASE_REF
          echo ${{ github.head_ref }} # GITHUB_HEAD_REF
          git diff $GITHUB_BASE_REF $GITHUB_HEAD_REF --name-only
      - name: Install xcaudit
        uses: Alexander-Ignition/XCAudit@main
      - name: Build and test
        run: swift test --enable-code-coverage --disable-automatic-resolution 2>&1 | xcaudit
        shell: bash
