name: Test
on:
  push:
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_12.app
      - name: Install XCAudit
        uses: Alexander-Ignition/XCAudit@v0.0.6
      - name: Test XCAudit
        run: |
          echo $PATH
          echo $GITHUB_PATH
          XCAudit
      - name: Build and test
        run: set -o pipefail && swift test --enable-code-coverage --disable-automatic-resolution 2>&1 | ./xc-gh
